# Generated by Django 3.0.4 on 2020-04-18 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rasiberryPiGPIOEquiptAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField()),
                ('deviceDataName', models.CharField(max_length=32)),
                ('deviceDataValue', models.CharField(max_length=32)),
                ('deviceUpdatedDataTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='device data time')),
            ],
            options={
                'verbose_name': '设备采集的数据',
                'verbose_name_plural': '设备采集的数据',
            },
        ),
        migrations.CreateModel(
            name='DeviceDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField()),
                ('deviceDataName', models.CharField(max_length=32)),
                ('deviceDataValue', models.CharField(max_length=32)),
                ('dataDateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='device data time')),
            ],
            options={
                'verbose_name': '设备数据的历史记录',
                'verbose_name_plural': '设备数据的历史记录',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=32)),
                ('deviceType', models.CharField(max_length=32)),
                ('deviceInterfaceType', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='DevicePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField()),
                ('pinMode', models.IntegerField()),
                ('pinFunction', models.IntegerField()),
            ],
            options={
                'verbose_name': '设备所需pin口',
                'verbose_name_plural': '设备所需pin口',
            },
        ),
        migrations.CreateModel(
            name='PiDeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=32)),
                ('deviceID', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='PiDevicePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField()),
                ('pinBoardID', models.IntegerField()),
                ('devicePinID', models.IntegerField()),
                ('pinValue', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '设备所需pin口',
                'verbose_name_plural': '设备所需pin口',
            },
        ),
    ]
