# Generated by Django 3.0.4 on 2020-04-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasiberryPiGPIOEquiptAPI', '0003_auto_20200419_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pideviceinfo',
            old_name='deviceName',
            new_name='piDeviceName',
        ),
    ]
