# Generated by Django 3.0.5 on 2020-04-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasiberryPiGPIOEquiptAPI', '0004_auto_20200419_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='deviceInCategory',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='i2cAddress',
            field=models.IntegerField(default=None),
        ),
    ]
