# Generated by Django 3.0.4 on 2020-04-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasiberryPiGPIOEquiptAPI', '0007_auto_20200424_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='deviceID',
            new_name='piDeviceID',
        ),
        migrations.RenameField(
            model_name='devicedatahistory',
            old_name='deviceID',
            new_name='piDeviceID',
        ),
    ]
