# Generated by Django 3.0.4 on 2020-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDataHistoryChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piDeviceID', models.IntegerField()),
                ('deviceDataName', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=36)),
                ('active', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': '设备数据图表',
                'verbose_name_plural': '设备数据图表',
            },
        ),
    ]
