# Generated by Django 3.0.4 on 2020-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasiberryPiGPIOEquiptHistoryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedatahistorychart',
            name='displayType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicedatahistorychart',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
