# Generated by Django 3.0.4 on 2020-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rasiberryPiGPIOBaseAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleName', models.CharField(max_length=32)),
                ('scheduleType', models.IntegerField(default=1)),
                ('scheduleMode', models.IntegerField(default=1)),
                ('scheduleValue', models.IntegerField(default=1)),
                ('otherSchedule', models.CharField(max_length=64)),
                ('scheduleJobName', models.CharField(max_length=32)),
                ('scheduleStatus', models.IntegerField(default=1)),
            ],
        ),
    ]
