# Generated by Django 3.0.4 on 2020-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasiberryPiGPIOBaseAPI', '0002_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='scheduleStatus',
            field=models.IntegerField(default=2),
        ),
    ]
