# Generated by Django 3.0.4 on 2020-04-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasiberryPiGPIOBaseAPI', '0003_auto_20200424_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduler',
            options={'verbose_name': '定时器', 'verbose_name_plural': '定时器'},
        ),
    ]
