# Generated by Django 3.0.4 on 2020-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasiberryPiGPIOBaseAPI', '0005_scheduler_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='piDeviceId',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
